### ISSUE TITLE
The navBar & hero section 

### ISSUE THREAD

**Issue by ayoub-bani** [ngMorocco/ngx-darija#1]
this issue just to let everyone know that I'm working on the navbar styling & the hero section

**Comment by chihab** [comment]
This comment to let everyone know that you're awesome @ayoub-bani!

**Comment by ayoubAnbara** [comment]
@ayoub-bani what's the framework CSS that you are used?

**Comment by ayoub-bani** [comment]
> @ayoub-bani what's the framework CSS that you are used?

i have sent a pull request containing Bootstrap 4

**Comment by chihab** [comment]
Closing because we chose not to use a css framework.
