### ISSUE TITLE
Improve Page SEO

### ISSUE THREAD

**Issue by chihab** [ngMorocco/ngx-darija#14]
Apply SEO recommandations provided by Lighthouse to have a better score

![image](https://user-images.githubusercontent.com/196852/110906618-77f01100-830c-11eb-94e5-17bca3be6ecd.png)

**Comment by rabraghib** [comment]
check out #39

**Comment by chihab** [comment]
Thanks a lot for you PR @rabraghib we've implemented basic SEO in next branch without using an external library. Feel free to add any relevant SEO info on the next branch.
Awesome work BTW!
