### ISSUE TITLE
We need to Allow Embedding Angular in Darija videos in Youtube settings !!

### ISSUE THREAD

**Issue by ikourfaln** [ngMorocco/ngx-darija#17]
I discover that Embedding Angular in Darija videos is disabled !!

When I embed the video:

![CaptureYT1](https://user-images.githubusercontent.com/9744226/110976894-c4197080-8361-11eb-8e1a-0947db150d3e.PNG)

after I click play, I get this error:

![CaptureYT2](https://user-images.githubusercontent.com/9744226/110976943-d398b980-8361-11eb-96d5-aeaffd9f3839.PNG)

## Solution:

We need to Turn on "allow embedding" in youtube video settings.
I don't know if there is an option to Turn on "allow embedding" on videos by default.

so this task if for video channel owner,  @chihab 😉

**Comment by ikourfaln** [comment]
it's working now !!
I think you did it, if so, you are fast 🚀 🚀 🚀

**Comment by chihab** [comment]
Done for all videos. Let me know if I missed any.

**Comment by ikourfaln** [comment]
LGTM
