### ISSUE TITLE
Home page sessions UI proposition

### ISSUE THREAD

**Issue by Mubramaj** [ngMorocco/ngx-darija#29]
This is just a UI/design proposition for the main sessions displayed on the home page.

We can do like this https://angular-university.io/my-courses with the cards and the shadow hover effect (with ngx-darija colors of course) 

If this is approved I can work on it

**Comment by ikourfaln** [comment]
Yes, why not  😃 
our current version is just a simple one to start, we need to work on some good designs.

So, what do you suggest ? keep the last session in one row (as a hero) and make the others as cards in two column grid ?

**Comment by chihab** [comment]
I opened this RFC issue to discuss the roadmap https://github.com/ngMorocco/ngx-darija/issues/31

**Comment by Mubramaj** [comment]
> Yes, why not 
> our current version is just a simple one to start, we need to work on some good designs.
> 
> So, what do you suggest ? keep the last session in one row (as a hero) and make the others as cards in two column grid ?

Yes exactly that's what I was thinking. Let's see the roadmap that Chihab opened
